# .github/workflows/deploy.yml

on:
  pull_request:
  push:
    branches: [deploy]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: |
          npm install
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/deploy'
        env:
          deploy_url: ${{ secrets.RENDERHOOK }}
        run: |
          curl "$deploy_url"